uploads = []
outputs = []

[[generated]]
id = "sZnYuB-2nikJ4Ijd8AYvz"
uri = "file://artifacts/portfolio/src/assets/profile.png"
type = "image"
title = "Architect portrait"

[[generated]]
id = "ubG90Rq5exgRFtG7LsLag"
uri = "file://artifacts/portfolio/src/assets/project-1.png"
type = "image"
title = "Minimalist pavilion"

[[generated]]
id = "81TZ_2VaWq0TLNj3C46cx"
uri = "file://artifacts/portfolio/src/assets/project-2.png"
type = "image"
title = "Modern chair design"

[[generated]]
id = "3BkzdEnSNCVo1fafCi9YY"
uri = "file://artifacts/portfolio/src/assets/project-3.png"
type = "image"
title = "Gallery interior"

[[generated]]
id = "-iWMlhuY2-RL5NMX5kviP"
uri = "file://artifacts/portfolio/src/assets/project-4.png"
type = "image"
title = "Espresso machine"
